### ISSUE TITLE
Command failed due to signal: Segmantation fault: 11

### ISSUE THREAD

**Issue by ttuygun** [RahulKatariya/Reactofire#11]
I encounted this error in Xcode 8 using Swift 3 compitable version of 2.0. I cleaned derived data or re-install pod from 1.1.0 cocoapods but it don't work. Any suggestion?

Thanks in advance

**Comment by rahul0x24** [comment]
This is a bug in Swift compiler and the work around right now is to use Fast, Whole Module Optimization in the debug configuration. Please refer the image below.

<img width="1206" alt="screen shot 2016-09-27 at 9 00 10 pm" src="https://cloud.githubusercontent.com/assets/1857415/18880589/fe6c78fa-84f5-11e6-8967-1ce959803167.png">

**Comment by ttuygun** [comment]
Thank you it solved. This issue can be added in README

**Comment by rahul0x24** [comment]
Added to Readme 👍🏻
