### ISSUE TITLE
Doesn't work with SPM

### ISSUE THREAD

**Issue by wadetregaskis** [RahulKatariya/Reactofire#17]
$ swift package fetch
Cloning https://github.com/Restofire/Restofire.git
HEAD is now at 885fdf5 Add pod trunk push script to automatically deploy to cocoapods
Resolved version: 2.1.0
Cloning https://github.com/Alamofire/Alamofire.git
HEAD is now at 668cc5a Added release notes to the CHANGELOG and bumped the version to 4.0.1.
Resolved version: 4.0.1
error: the package has an unsupported layout, unexpected source file(s) found: …/Packages/Alamofire-4.0.1/Tests/AFError+AlamofireTests.swift, …/Packages/Alamofire-4.0.1/Tests/AuthenticationTests.swift, …/Packages/Alamofire-4.0.1/Tests/BaseTestCase.swift, …/Packages/Alamofire-4.0.1/Tests/CacheTests.swift, …/Packages/Alamofire-4.0.1/Tests/DownloadTests.swift, …/Packages/Alamofire-4.0.1/Tests/FileManager+AlamofireTests.swift, …/Packages/Alamofire-4.0.1/Tests/MultipartFormDataTests.swift, …/Packages/Alamofire-4.0.1/Tests/NetworkReachabilityManagerTests.swift, …/Packages/Alamofire-4.0.1/Tests/ParameterEncodingTests.swift, …/Packages/Alamofire-4.0.1/Tests/RequestTests.swift, …/Packages/Alamofire-4.0.1/Tests/ResponseSerializationTests.swift, …/Packages/Alamofire-4.0.1/Tests/ResponseTests.swift, …/Packages/Alamofire-4.0.1/Tests/ResultTests.swift, …/Packages/Alamofire-4.0.1/Tests/ServerTrustPolicyTests.swift, …/Packages/Alamofire-4.0.1/Tests/SessionDelegateTests.swift, …/Packages/Alamofire-4.0.1/Tests/SessionManagerTests.swift, …/Packages/Alamofire-4.0.1/Tests/String+AlamofireTests.swift, …/Packages/Alamofire-4.0.1/Tests/TLSEvaluationTests.swift, …/Packages/Alamofire-4.0.1/Tests/URLProtocolTests.swift, …/Packages/Alamofire-4.0.1/Tests/UploadTests.swift, …/Packages/Alamofire-4.0.1/Tests/ValidationTests.swift
fix: move the file(s) inside a module

$ swift package generate-xcodeproj
error: the package has an unsupported layout, unexpected source file(s) found: …/Packages/Alamofire-4.0.1/Tests/AFError+AlamofireTests.swift, …/Packages/Alamofire-4.0.1/Tests/AuthenticationTests.swift, …/Packages/Alamofire-4.0.1/Tests/BaseTestCase.swift, …/Packages/Alamofire-4.0.1/Tests/CacheTests.swift, …/Packages/Alamofire-4.0.1/Tests/DownloadTests.swift, …/Packages/Alamofire-4.0.1/Tests/FileManager+AlamofireTests.swift, …/Packages/Alamofire-4.0.1/Tests/MultipartFormDataTests.swift, …/Packages/Alamofire-4.0.1/Tests/NetworkReachabilityManagerTests.swift, …/Packages/Alamofire-4.0.1/Tests/ParameterEncodingTests.swift, …/Packages/Alamofire-4.0.1/Tests/RequestTests.swift, …/Packages/Alamofire-4.0.1/Tests/ResponseSerializationTests.swift, …/Packages/Alamofire-4.0.1/Tests/ResponseTests.swift, …/Packages/Alamofire-4.0.1/Tests/ResultTests.swift, …/Packages/Alamofire-4.0.1/Tests/ServerTrustPolicyTests.swift, …/Packages/Alamofire-4.0.1/Tests/SessionDelegateTests.swift, …/Packages/Alamofire-4.0.1/Tests/SessionManagerTests.swift, …/Packages/Alamofire-4.0.1/Tests/String+AlamofireTests.swift, …/Packages/Alamofire-4.0.1/Tests/TLSEvaluationTests.swift, …/Packages/Alamofire-4.0.1/Tests/URLProtocolTests.swift, …/Packages/Alamofire-4.0.1/Tests/UploadTests.swift, …/Packages/Alamofire-4.0.1/Tests/ValidationTests.swift
fix: move the file(s) inside a module

$ swift --version
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9

**Comment by rahul0x24** [comment]
Can you try version 2.2.0 which i have just updated. It should work 👍
