### ISSUE TITLE
XCODE 9 UrlError.Code error

### ISSUE THREAD

**Issue by nkarataev** [RahulKatariya/Reactofire#19]
Error occurred - Type 'URLError.Code' does not conform to protocol 'Hashable' in struct Retry
public var retryErrorCodes: Set<URLError.Code> = [.timedOut,
                                            .cannotFindHost,
                                            .cannotConnectToHost,
                                            .dnsLookupFailed,
                                            .networkConnectionLost
    ]

**Comment by rahul0x24** [comment]
Cannot reproduce this anymore. Closing.
