### ISSUE TITLE
Feature: Request Delegates

### ISSUE THREAD

**Issue by rahul0x24** [RahulKatariya/Reactofire#32]
Request Delegates inspired by @codeOfRobin talk about http://khanlou.com/2017/01/request-behaviors/ at Swift Delhi Meetup
It will require refactoring Request, Upload and Download Operations to reuse the code.

**Comment by codeOfRobin** [comment]
Oooh!

**Comment by codeOfRobin** [comment]
This sees like a good idea! Doesn't solve things like Linux compatibility (cos Alamofire doesn't work on Linux quite yet) but is otherwise really cool 👍

**Comment by rahul0x24** [comment]
Yes sad but @alamofire has it in its scope for 5.0. Thanks!
