### ISSUE TITLE
Feature: Support internet connectivity with Alamofire Protocols

### ISSUE THREAD

**Issue by rahul0x24** [RahulKatariya/Reactofire#37]

**Comment by theScud** [comment]
description of what you need for the feature?

**Comment by rahul0x24** [comment]
Restofire.Requestable has a variable waitsForInternetConnectivity which makes the request and if it failed due to not connected to internet error then it puts the request inside a eventuallyQueue which resumes when the network connection is established.

The implementation is a little tricky to support this in Alamofire Protocols so closing this for now.
