### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by Gargo** [RahulKatariya/Reactofire#43]
Just downloaded your library and tried to run example (I prefer cocoa pods) - nothing works

**Comment by rahul0x24** [comment]
I verified that `pod try Restofire` is broken, meanwhile you can download the project and run example.

**Comment by rahul0x24** [comment]
You can also check the blog post for a better example - https://medium.com/rahulkatariya/clean-architecture-networking-in-swift-185ee4855a15
