### ISSUE TITLE
Swift Package Manager installation does not work

### ISSUE THREAD

**Issue by ghost** [RahulKatariya/Reactofire#44]
First of all thanks for an awesome looking project. Can't wait to try it out! 🎉 

- [x] I've read, understood, and done my best to follow the [CONTRIBUTING guidelines](https://github.com/Restofire/Restofire/blob/master/CONTRIBUTING.md).

## What did you do?

- Tried to install Restofire with _Swift Package Manager - Swift 4.1.0 (swiftpm-14050)_

## What did you expect to happen?

- Restofire and it's dependencies being downloaded and linked with my package

## What happened instead?

- A build error. More specifically, a _manifest parse error_ of Restofire's `Package.swift` when running `swift build`:

```
$ RestofireTest swift build
Updating https://github.com/Restofire/Restofire.git
https://github.com/Restofire/Restofire.git @ 4.0.0: error: manifest parse error(s):
/var/folders/jf/jlrsnxnx5pz247ctyynyjlgm0000gn/T/TemporaryFile.8zoWzT.swift:34:70: error: type 'Version' has no member 'upToNextMajor'
        .Package(url: "https://github.com/Alamofire/Alamofire.git", .upToNextMajor(from: "4.5.0"))
                                                                     ^~~~~~~~~~~~~
```

## My Findings 💡 

`upToNextMajor` has been introduced in [V4](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md) of the package description API.

Interestingly, if I clone Restofire and run `swift package tools-version` it outputs `3.1.0`.
This is the [default version](https://swift.org/blog/swift-package-manager-manifest-api-redesign/) if you do not specify a tools version. 

Restofire does specify `// swift-tools-version:4.0` in it's `Package.swift`. However, this [needs to be done in the first line](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#swift-tools-version-specification) of the file (which is [not the case](https://github.com/Restofire/Restofire/blob/54909da6dc52c387412d4e5a341c6c54b417fb44/Package.swift#L27) for Restofire).

The issue can probably be fixed by moving `// swift-tools-version:4.0` from its current position in `Package.swift` to the top of the file.

👉 _If it's ok with you, I'd be happy to try this out and submit a pull request if it works!_ 🤓 🙏 

## Restofire Environment

**Restofire version:** 4.0.0
**Xcode version:** Version 9.3 (9E145) (did not use Restofire in Xcode, though)
**Swift version:** Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)
**Platform(s) running Restofire:** macOS
**macOS version running Xcode:** macOS HighSierra Version 10.13.3

## Demo Project

Just set up an empty Swift Package and try to install Restofire:

```
$ mkdir RestofireTest
$ cd RestofireTest
$ swift package init
```

then edit `Package.swift`:

``` swift
// swift-tools-version:4.0

import PackageDescription

let package = Package(
    name: "RestofireTest",
    products: [
        .library(name: "RestofireTest", targets: ["RestofireTest"]),
    ],
    dependencies: [
        .package(url: "https://github.com/Restofire/Restofire.git", .upToNextMajor(from: "4.0.0"))
    ],
    targets: [
        .target(name: "RestofireTest", dependencies: ["Restofire"])
    ]
)
```

**Comment by rahul0x24** [comment]
Thanks and Sure, I am happy to review your pull request if you have a solution already.

**Comment by ghost** [comment]
👉  See #45.

**Comment by rahul0x24** [comment]
@dnlggr You might also like https://medium.com/rahulkatariya/generating-swift-network-code-using-aarkay-64ad6d49d337. 

As every request is independent using Restofire, It makes it easy to autogenerate all APIs.

It's in a very early phase. If it interests you then here is the slack community to discuss more - https://aarkay.herokuapp.com.

Any feedback is appreciated! 🍻
