### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by gerchicov-bp** [RahulKatariya/Reactofire#47]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Restofire/Restofire/blob/master/CONTRIBUTING.md).

## What did you do?

Copied some code from readme.

## What did you expect to happen?

The project is compiled

## What happened instead?

```
self.path += path
Value of optional type 'String?' must be unwrapped to a value of type 'String'
```
you can't apply `+=` to `String?` and `String` variables.

## Restofire Environment

**Restofire version:** 4.0.1
**Xcode version:** 11.2.1
**Swift version:** 5
**Platform(s) running Restofire:** iOS
**macOS version running Xcode:** 10.15.1

## Demo Project

```
import Foundation
import Restofire

protocol NYConfigurable: Configurable {}
protocol NYRequestable: Requestable, NYConfigurable {}

extension Restofire.DataResponseSerializable where Response: Decodable {
    public var responseSerializer: DataResponseSerializer<Response> {
        return DataRequest.JSONDecodableResponseSerializer()
    }
}

struct UserInfoGETService: NYRequestable {
    typealias Response = FSUserInfoModel
    var path: String?
    var parameters: Any?

    init(path: String, parameters: Any) {
        self.path += path
        self.parameters = parameters
    }
}
```
in general why `+=`? Maybe simply `=`?

**Comment by rahul0x24** [comment]
Thank you for pointing it out. It should be `self.path = path` or if you want to send some dynamic value like user id then you can append to the path like below
```
struct UserInfoGETService: NYRequestable {
    typealias Response = FSUserInfoModel
    var path: String = "user/"

    init(path: String) {
        self.path += path
    }
}
```

**Comment by gerchicov-bp** [comment]
@RahulKatariya additionally you write constructor `init(path: String, parameters: Any) { ... }` but the next code chunk uses another constructor - `init(parameters: Any)`.
Could you please update conflicting code in your readme?

**Comment by rahul0x24** [comment]
@gerchicov-bp Thanks again!. Give me some time and I will update the Readme. Meanwhile, here is an example that should work for you ~~if you are willing to upgrade the code to the latest swift version~~ - https://medium.com/rahulkatariya/clean-architecture-networking-in-swift-185ee4855a15.

**Comment by rahul0x24** [comment]
The examples in the Readme should work now. Closing this issue!
